### ISSUE TITLE
Unrecognized field name "Annotation"

### ISSUE THREAD

**Issue by nleroy917** [pjgwynne/iBB151#1]
Hey guys,

I'm trying to load in the SBML model into cobra toolbo using `readCbModel` from this repo. The code is really simple:

```matlab
readCbModel('iBB151_sbml.xml', 'fileType', 'SMBL')
```
But it gives the following error:
```
>>> Unrecognized field name "Annotation"
```

I'm using MATLAB R2022b and the most recent version of cobra straight from their github.

Any help is appreciated! Thanks!

**Comment by nleroy917** [comment]
Small update: I can debug the code and **sometimes** it loads, sometimes it doesn't, and I cant figure out a pattern!

**Comment by pjgwynne** [comment]
how embarassing - i'll take a look later today and see if i can replicate the error.

**Comment by pjgwynne** [comment]
i don't think i understand why (the 'annotation' fields look the same?) but a version i re-exported from cobra just now seems to import fine in my hands. do you want to try the new file i just uploaded 'newSBML.xml'?

**Comment by pjgwynne** [comment]
FYI I just changed the name to 'updated_iBB151_SBML.xml' to make it more obvious if anyone else comes looking.

**Comment by nleroy917** [comment]
> i don't think i understand why (the 'annotation' fields look the same?) but a version i re-exported from cobra just now seems to import fine in my hands. do you want to try the new file i just uploaded 'newSBML.xml'?

I don't either, but the newly uploaded model works just fine! Thank you so much for doing that.
